name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  # Used by the manifest-inspect check
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Register binfmt handlers so we can build arm64 on amd64 runners
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Create and use a Buildx builder instance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Scrape latest download info
        id: scrape
        shell: bash
        run: |
          set -euo pipefail
          page=$(curl -s https://necessegame.com/server/)
          rel=$(echo "$page" | grep -Eo 'content/server/[0-9]{1,2}-[0-9]{1,2}-[0-9]{1,2}-[0-9]+/necesse-server-linux64-[0-9]{1,2}-[0-9]{1,2}-[0-9]{1,2}-[0-9]+\.zip' | head -n 1 || true)
          if [[ -z "${rel}" ]]; then
            echo "Could not find server download URL on necessegame.com/server/"
            exit 1
          fi
          url="https://necessegame.com/${rel}"
          fname=$(basename "$url")
          vb=${fname#necesse-server-linux64-}
          vb=${vb%.zip}
          version=$(echo "$vb" | grep -Eo '^[0-9]{1,2}-[0-9]{1,2}-[0-9]{1,2}')
          build=$(echo "$vb" | grep -Eo '[0-9]+$')
          echo "Found: url=$url, version=$version, build=$build"
          echo "url=$url" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "build=$build" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image already exists
        id: check
        shell: bash
        env:
          VERSION: ${{ steps.scrape.outputs.version }}
          BUILD: ${{ steps.scrape.outputs.build }}
        run: |
          set -euo pipefail
          TAG="${VERSION}-${BUILD}"
          if ! docker manifest inspect "${DOCKER_IMAGE}:${TAG}" >/tmp/manifest.json 2>/dev/null; then
            echo "Tag not found; will build."
            echo "should_build=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if grep -q '"architecture":\s*"arm64"' /tmp/manifest.json && grep -q '"architecture":\s*"amd64"' /tmp/manifest.json; then
            echo "Both amd64 and arm64 already present — skipping build."
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          else
            echo "Multi-arch not complete (will build/push for missing arch)."
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            # version-build (e.g., 1-0-1-20436084)
            type=raw,value=${{ steps.scrape.outputs.version }}-${{ steps.scrape.outputs.build }}
            # version only
            type=raw,value=${{ steps.scrape.outputs.version }}
            # latest only on default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        if: steps.check.outputs.should_build == 'true'
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            url=${{ steps.scrape.outputs.url }}
            version=${{ steps.scrape.outputs.version }}
            build=${{ steps.scrape.outputs.build }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Done (no build necessary)
        if: steps.check.outputs.should_build != 'true'
        run: echo "Already up to date; no new server release detected."